#cloud-config
users:
  - name: ansible
    groups: sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHhngpKEDbyEAo0263DrG/bEvodabgm1H5qEkHKephkT

ssh_pwauth: false

runcmd:
  - ip link set enp0s8 up || true
  - dhclient enp0s8 || true
  - ip link set eth1 up || true
  - dhclient eth1 || true