---
- name: Базові налаштування (користувачі та варіант)
  hosts: all
  become: yes
  roles:
    - base

- name: Налаштування бази даних (MariaDB)
  hosts: db
  become: yes
  roles:
    - db

- name: Налаштування веб-застосунку та Nginx
  hosts: workers
  become: yes
  roles:
    - web